m1<- matrix(1:20, nrow=5, ncol=4, byrow=TRUE)
rownames(m1)<- c("Row 1", "Row 2", "Row 3", "Row 4", "Row 5")
colnames(m1)<- c("Column 1","Column 2","Column 3", "Column 4")
m2<- matrix(1:9,nrow=3,ncol=3)
rownames(m2)<- c("Row A","Row B","Row C")
colnames<- c("Col X", "Col Y", "Col Z")
m3<- matrix(1:4,nrow=2,ncol=2)
rownames(m3)<-c("Row P", "Row Q")
colnames(m3)<-c("Row R", "Row S")
print(m1)
print(m2)
print(m3)