n <- c(1,2,3,4,5)
c <- c("apple","banana","orange")
l <- c(TRUE,FALSE,TRUE)
cat("Numeric vector:",n)
cat("Character vector:",c)
cat("Logical vector:",l)
cat("Type of n:",class(n))
cat("Type of c:",class(c))
cat("Type of l:",class(l))